### ISSUE TITLE
HTTPS for api.sikher.com

### ISSUE THREAD

**Issue by inderpreet99** [sikher/gurbanidb#11]
Can we add HTTPS for api.sikher.com?

I use the API for a hukamnama display site. It has been working pretty nicely. Thanks for that. I'd like to convert the site over to HTTPS. Having the api.sikher.com site be HTTP only is a problem, since I can't make http requests on an HTTPS site. I can try to proxy it, but I'd like to avoid that if we can just add the feature that would benefit all.

Thanks for all the hard work!

**Comment by jasdeepkhalsa** [comment]
This is now available in both http & https
