### ISSUE TITLE
api not responding to the search by first letters from start or first start from anywhere

### ISSUE THREAD

**Issue by sukhpalsingh** [sikher/gurbanidb#4]
I was looking at iGurbani app which you have for demo and it seems not working. I looked into the cause of the issue and i found that api is not responding to the search by first letters.

I was trying using following url for api search:
http://api.sikher.com/search/1/abskb

and i getting response on the page as follows:
The page or endpoint you requested could not be found

**Comment by irvanjitsingh** [comment]
Try searching using unicode Gurmukhi characters instead. I don't think the API maps english characters to their gurmukhi 'counterparts' but that might be a feature worth adding in the future.

**Comment by sukhpalsingh** [comment]
Ok thanks. I recently added new column to the gurbanidb for ascii/english characters with ascii scripture and ascii search columns and it can be used by other people too as not all support unicode support yet.

are you happy if I add this to your gurbanidb?

**Comment by jujhars13** [comment]
vjkkvjkf

You could either add it to the db, but wouldn't it be better just to create a method that translates between unicode -> ascii and ascii <- unicode?  You'll keep the DB light that way, otherwise you'll increase it's size by about 40%

**Comment by sukhpalsingh** [comment]
i was thinking the same too. But i did created an apprication before which translate unicode to ascii and it gets quiet slower by doing so.

I do not think the size of db will increase, as you will either keep either ascii or unicode as it depends what type of application you going to build and what platform you going to support. Not all platform support unicode so if u going to build for everyone then you should choose ascii otherwise unicode.

**Comment by jasdeepkhalsa** [comment]
Sukhpal, thanks for the additions. Please do send them over and we'll take a look at folding them into the core database. In the meanwhile I'll close this issue as it was almost certainly due to not using unicode Gurmukhi characters.
